 name: Blog post workflow
on:
  schedule:
    # Runs every day at 3pm UTC (11pm SG)
    - cron: '0 1 * * *'
     - cron: "0 */6 * * *" 

jobs:
  pull_blog_rss:
    name: AutoUpdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://blog.rongying.co/feed.xml
          count: 6 # default 5
      - name: Commit file changes
        - run: git status  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
